const Indeed = require("../models/indeed.model");
const LinkedIn = require("../models/linkedin.model");

const JOB_BOARDS = [Indeed, LinkedIn];

const SKILL_SET =[
    {skill : 'Java', count : 0},
    {skill : 'REST', count : 0}, 
    {skill : 'React', count : 0},
    {skill : 'C++', count : 0},
    {skill : 'JavaScript', count : 0},
    {skill : 'ReactJS', count : 0},
    {skill : 'NodeJS', count : 0},
    {skill : 'SQL', count : 0},
    {skill : 'MongoDB', count : 0},
    {skill : 'Python', count : 0},
    {skill : '.NET', count : 0},
    {skill : 'Ruby', count : 0},
    {skill : 'Golang', count : 0},
    {skill : 'Distributed Systems', count : 0},
    {skill : 'Back end', count : 0},
    {skill : 'Front end', count : 0},
    {skill : 'Full Stack', count : 0},
    {skill : 'CSS', count : 0},
    {skill : 'HTML', count : 0},
    {skill : 'Messaging Queue', count : 0},
    {skill : 'Docker', count : 0},
    {skill : 'Redis', count : 0},
    {skill : 'Redux', count : 0},
    {skill : 'Kafka', count : 0},
    {skill : 'AWS', count : 0},
    {skill : 'J2EE', count : 0},
    {skill : 'Spring', count : 0},
    {skill : 'PHP', count : 0},
    {skill : 'Express', count : 0},
    {skill : 'WordPress', count : 0},
    {skill : 'C#', count : 0},
    {skill : 'gRPC', count : 0},
    {skill : 'Web Developer', count : 0},
    {skill : 'Kubernetes', count : 0},
    {skill : 'Cloud', count : 0},
    {skill : 'DevOps', count : 0},
    {skill : 'Google Cloud Platform', count : 0},
    {skill : 'Azure', count : 0},
    {skill : 'Elixir', count : 0},
    {skill : 'Angular', count : 0},
    {skill : 'Vue', count : 0},
    {skill : 'SOAP', count : 0},
    {skill : 'CI/CD', count : 0},
    {skill : 'Cassandra', count : 0},
    {skill : 'MySQL', count : 0},
    {skill : 'Oracle', count : 0},
    {skill : 'Linux', count : 0},
    {skill : 'Machine Learning', count : 0},
    {skill : 'Computer Vision', count : 0},
    {skill : 'TypeScript', count : 0},
    {skill : 'React Native', count : 0},
    {skill : 'Object-Oriented', count : 0},
    {skill : 'Hadoop', count : 0},
    {skill : 'GraphQL', count : 0},
    {skill : 'Swift', count : 0},
    {skill : 'Express', count : 0},
    {skill : 'AWS Lambda', count : 0},
    {skill : 'Rails', count : 0},
    {skill : 'MVC', count : 0},
    {skill : 'PostgreSQL', count : 0},
    {skill : 'Kotlin', count : 0},
    {skill : 'iOS', count : 0},
    {skill : 'Android', count : 0},
    {skill : 'gaming', count : 0},
    {skill : 'networking', count : 0},
    {skill : 'TCP', count : 0},
    {skill : 'Embedded', count : 0},
    {skill : 'NoSQL', count : 0},
    {skill : 'Rust', count : 0},
    {skill : 'Perl', count : 0},
    {skill : 'Computer Network', count : 0},
    {skill : 'Git', count : 0},
    {skill : 'Data Structures', count : 0},
    {skill : 'Data Science', count : 0}, 
    {skill : 'Android', count : 0},

    
];

exports.JOB_BOARDS = JOB_BOARDS;
exports.SKILL_SET = SKILL_SET;
